### ISSUE TITLE
S.3.3 Autofill Job Applications

### ISSUE THREAD

**Issue by MatthewBeaulieu0** [cckarabatsos/SOEN390_Team13#142]
- [x] Backend  Autofill Job Applications
- [ ] Frontend  Autofill Job Applications
- [x] Frontend: Have a manual input option for application
- [ ] Frontend: Have an import cv button that fetches file and auto fills textboxes
- [ ] Frontend: Required spaces not filled to be red starred for user.
- [ ] Frontend: User to be signed in to apply.

Associated Tasks:

- #159 
- #160 
- #161 
- #162 
- #164 
- [x] #217
- [x] #218

**Comment by Bogdanpoda** [comment]
I don't use of backend routes for autofill a job application since the information can be fetched and locally stored once a user logs in

**Comment by dzm-fiodarau** [comment]
> I don't use of backend routes for autofill a job application since the information can be fetched and locally stored once a user logs in
We still need to implement storing different applications like a list of where a user has applied so he could view it right?
