### ISSUE TITLE
Parse PDF in the Backend and Save Info as Application Form in Database

### ISSUE THREAD

**Issue by dzm-fiodarau** [cckarabatsos/SOEN390_Team13#162]
Associated User Story #142 

Accept a PDF file and parse the text inside it saving relevant information as an Application Form entity in the database.

**Comment by MatthewBeaulieu0** [comment]
If we cannot parse the pdf easily we should check into tools that could help us

**Comment by dzm-fiodarau** [comment]
> If we cannot parse the pdf easily we should check into tools that could help us

I think I found a library to dothat but it will be the latest thing I will work on during this sprint. We will have to talk about how it should work too I want to be sure on what we want.

**Comment by MatthewBeaulieu0** [comment]
Ok perf

**Comment by dzm-fiodarau** [comment]
This feature will not be implemented. Applications will be done in a different way.
