### ISSUE TITLE
company entity + logic

### ISSUE THREAD

**Issue by Bogdanpoda** [cckarabatsos/SOEN390_Team13#190]
we need a company entity under which all the company job postings would be attached too
- [x] Add job posting array
- [x] Add application arrays with documents 
- [x] Add new follow routes to follow companies or unfollow them 
- [x] Removed companies from user search

**Comment by MatthewBeaulieu0** [comment]
I changed the due date to resolve 2 sprint bugs since i might have a little bit of time
